# Generated by Django 5.2.11 on 2026-03-23 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Имя должно начинаться с заглавной буквы и содержать только буквы', regex='^[А-ЯЁ][а-яё]+(?:-[А-ЯЁ][а-яё]+)?$')]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Имя должно начинаться с заглавной буквы и содержать только буквы', regex='^[А-ЯЁ][а-яё]+(?:-[А-ЯЁ][а-яё]+)?$')]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Номер телефона должен быть в формате 10 цифр после +7', regex='^\\+7\\d{10}$')], verbose_name='phone number'),
        ),
    ]
