# Generated by Django 5.2.11 on 2026-04-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
